application: apprtc
version: 2
runtime: python27
threadsafe: true
api_version: 1
default_expiration: "2h"

handlers:
- url: /html
  static_dir: html

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /probe.*
  script: probers.app
  secure: always

- url: /.*
  script: apprtc.app
  secure: always

libraries:
- name: jinja2
  version: latest
- name: ssl
  version: latest
- name: pycrypto
  version: latest

env_variables:
  BYPASS_JOIN_CONFIRMATION: false
