# Copyright 2015 Google Inc. All Rights Reserved.

"""AppRTC Constants.

This module contains the constants used in AppRTC Python modules.
"""
import json
import os

ROOM_MEMCACHE_EXPIRATION_SEC = 60 * 60 * 24
ROOM_MEMCACHE_RETRY_LIMIT = 100

LOOPBACK_CLIENT_ID = 'LOOPBACK_CLIENT_ID'

TURN_BASE_URL = 'https://computeengineondemand.appspot.com'
TURN_URL_TEMPLATE = '%s/turn?username=%s&key=%s'
CEOD_KEY = '4080218913'

WSS_HOST_PORT_PAIR = 'apprtc-ws.webrtc.org:443'

RESPONSE_INTERNAL_ERROR = 'ERR_INTERNAL'
RESPONSE_ROOM_FULL = 'ERR_ROOM_FULL'
RESPONSE_DUPLICATE_CLIENT = 'ERR_DUPLICATE_CLIENT'

RESPONSE_INVALID_CALLEE = 'ERR_INVALID_CALLEE'
RESPONSE_INVALID_CALLER = 'ERR_INVALID_CALLER'
RESPONSE_INVALID_ROOM = 'ERR_INVALID_ROOM'
RESPONSE_INVALID_ARGUMENT = 'ERR_INVALID_ARG'
RESPONSE_INVALID_STATE = 'ERR_INVALID_STATE'
RESPONSE_INVALID_CODE = 'ERR_INVALID_CODE'
RESPONSE_INVALID_USER = 'ERR_INVALID_USER'
RESPONSE_NOT_FOUND = 'ERR_NOT_FOUND'

RESPONSE_CODE_SENT = 'CODE_SENT'
RESPONSE_CODE_RESENT = 'CODE_RESENT'
RESPONSE_UNVERIFIED = 'UNVERIFIED'
RESPONSE_VERIFIED = 'VERIFIED'
RESPONSE_SUCCESS = 'SUCCESS'
RESPONSE_INVALID_REQUEST = "INVALID_REQUEST"

IS_DEV_SERVER = os.environ.get('APPLICATION_ID', '').startswith('dev')

ACTION_CALL = 'call'
ACTION_ACCEPT = 'accept'

PARAM_ACTION = 'action'
PARAM_CALLER_ID = 'callerId'
PARAM_CALLER_GCM_ID = 'callerGcmId'
PARAM_CALLEE_ID = 'calleeId'
PARAM_CALLEE_GCM_ID = 'calleeGcmId'
PARAM_USER_GCM_ID = 'userGcmId'
PARAM_MESSAGE = 'message'
PARAM_ROOM_ID = 'roomId'

BIGQUERY_URL = 'https://www.googleapis.com/auth/bigquery'

# Dataset used in production.
BIGQUERY_DATASET_PROD = 'prod'

# Dataset used when running locally.
BIGQUERY_DATASET_LOCAL = 'dev'

# BigQuery table within the dataset.
BIGQUERY_TABLE = 'analytics'
